# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandColumnInfo',
            fields=[
                ('dc_id', models.AutoField(db_column='DC_id', primary_key=True, serialize=False)),
                ('column_name_cn', models.CharField(max_length=30)),
                ('column_name_en', models.CharField(blank=True, max_length=30, null=True)),
                ('extraction_rule', models.CharField(blank=True, max_length=100, null=True)),
                ('extraction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'demand_column_info',
            },
        ),
        migrations.CreateModel(
            name='SpiderDemandInfo',
            fields=[
                ('d_id', models.AutoField(db_column='D_id', primary_key=True, serialize=False)),
                ('d_code', models.CharField(db_column='D_code', max_length=32)),
                ('demand_name', models.CharField(max_length=30)),
                ('demand_department', models.CharField(max_length=20)),
                ('priority_level', models.CharField(blank=True, max_length=10, null=True)),
                ('channel_name', models.CharField(max_length=30)),
                ('data_type', models.CharField(max_length=20)),
                ('proposer', models.CharField(blank=True, max_length=20, null=True)),
                ('is_app', models.IntegerField()),
                ('start_url', models.CharField(blank=True, max_length=300, null=True)),
                ('spider_rate', models.CharField(blank=True, max_length=10, null=True)),
                ('upload_doc', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('examine_status', models.IntegerField()),
                ('task_executor', models.CharField(blank=True, max_length=20, null=True)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'spider_demand_info',
            },
        ),
    ]
